/**
 * This class is generated by jOOQ
 */
package com.webonise.mycurd.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Studentinfo implements Serializable {

    private static final long serialVersionUID = -2005452080;

    private final String  name;
    private final Integer age;
    private final String  class_;
    private final Integer rollno;
    private final Integer _Id;

    public Studentinfo(Studentinfo value) {
        this.name = value.name;
        this.age = value.age;
        this.class_ = value.class_;
        this.rollno = value.rollno;
        this._Id = value._Id;
    }

    public Studentinfo(
        String  name,
        Integer age,
        String  class_,
        Integer rollno,
        Integer _Id
    ) {
        this.name = name;
        this.age = age;
        this.class_ = class_;
        this.rollno = rollno;
        this._Id = _Id;
    }

    public String getName() {
        return this.name;
    }

    public Integer getAge() {
        return this.age;
    }

    public String getClass_() {
        return this.class_;
    }

    public Integer getRollno() {
        return this.rollno;
    }

    public Integer get_Id() {
        return this._Id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Studentinfo (");

        sb.append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(class_);
        sb.append(", ").append(rollno);
        sb.append(", ").append(_Id);

        sb.append(")");
        return sb.toString();
    }
}
