/**
 * This class is generated by jOOQ
 */
package com.webonise.mycurd.tables.records;


import com.webonise.mycurd.tables.Studentinfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentinfoRecord extends UpdatableRecordImpl<StudentinfoRecord> implements Record5<Integer, String, Integer, String, Integer> {

    private static final long serialVersionUID = -468333308;

    /**
     * Setter for <code>student.studentinfo._id</code>.
     */
    public void set_Id(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>student.studentinfo._id</code>.
     */
    public Integer get_Id() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>student.studentinfo.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>student.studentinfo.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>student.studentinfo.age</code>.
     */
    public void setAge(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>student.studentinfo.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>student.studentinfo.class</code>.
     */
    public void setClass_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>student.studentinfo.class</code>.
     */
    public String getClass_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>student.studentinfo.rollno</code>.
     */
    public void setRollno(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>student.studentinfo.rollno</code>.
     */
    public Integer getRollno() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Studentinfo.STUDENTINFO._ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Studentinfo.STUDENTINFO.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Studentinfo.STUDENTINFO.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Studentinfo.STUDENTINFO.CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Studentinfo.STUDENTINFO.ROLLNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return get_Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getClass_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRollno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentinfoRecord value1(Integer value) {
        set_Id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentinfoRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentinfoRecord value3(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentinfoRecord value4(String value) {
        setClass_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentinfoRecord value5(Integer value) {
        setRollno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentinfoRecord values(Integer value1, String value2, Integer value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentinfoRecord
     */
    public StudentinfoRecord() {
        super(Studentinfo.STUDENTINFO);
    }

    /**
     * Create a detached, initialised StudentinfoRecord
     */
    public StudentinfoRecord(Integer _Id, String name, Integer age, String class_, Integer rollno) {
        super(Studentinfo.STUDENTINFO);

        set(0, _Id);
        set(1, name);
        set(2, age);
        set(3, class_);
        set(4, rollno);
    }
}
