/**
 * This class is generated by jOOQ
 */
package com.webonise.mycurd;


import com.webonise.mycurd.tables.Studentinfo;
import com.webonise.mycurd.tables.records.StudentinfoRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>student</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<StudentinfoRecord, Integer> IDENTITY_STUDENTINFO = Identities0.IDENTITY_STUDENTINFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<StudentinfoRecord> KEY_STUDENTINFO_PRIMARY = UniqueKeys0.KEY_STUDENTINFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<StudentinfoRecord, Integer> IDENTITY_STUDENTINFO = createIdentity(Studentinfo.STUDENTINFO, Studentinfo.STUDENTINFO._ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<StudentinfoRecord> KEY_STUDENTINFO_PRIMARY = createUniqueKey(Studentinfo.STUDENTINFO, "KEY_studentinfo_PRIMARY", Studentinfo.STUDENTINFO._ID);
    }
}
