/**
 * This class is generated by jOOQ
 */
package com.webonise.mycurd;


import com.webonise.mycurd.tables.Studentinfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student extends SchemaImpl {

    private static final long serialVersionUID = 1382962763;

    /**
     * The reference instance of <code>student</code>
     */
    public static final Student STUDENT = new Student();

    /**
     * The table <code>student.studentinfo</code>.
     */
    public final Studentinfo STUDENTINFO = com.webonise.mycurd.tables.Studentinfo.STUDENTINFO;

    /**
     * No further instances allowed
     */
    private Student() {
        super("student", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Studentinfo.STUDENTINFO);
    }
}
