/**
 * This class is generated by jOOQ
 */
package com.webonise.mycurd;


import com.webonise.mycurd.tables.Studentinfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in student
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>student.studentinfo</code>.
     */
    public static final Studentinfo STUDENTINFO = com.webonise.mycurd.tables.Studentinfo.STUDENTINFO;
}
